---
# Source: elasticsearch/templates/coordinating/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: elasticsearch-coordinating
  namespace: "cti-svcs-cdso-gdk-169643"
  labels:
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/version: 8.12.0
    helm.sh/chart: elasticsearch-19.17.2
    app.kubernetes.io/component: coordinating-only
automountServiceAccountToken: false
