---
# Source: elasticsearch/charts/kibana/templates/secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch-kibana
  namespace: "cti-svcs-cdso-gdk-169643"
  labels:
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kibana
    app.kubernetes.io/version: 8.12.0
    helm.sh/chart: kibana-10.8.0
type: Opaque
data:
  kibana-password: S2liYW5hQWRtaW4=
