---
# Source: elasticsearch/templates/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: elasticsearch
  namespace: "cti-svcs-cdso-gdk-169643"
  labels:
    app.kubernetes.io/instance: elasticsearch
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: elasticsearch
    app.kubernetes.io/version: 8.12.0
    helm.sh/chart: elasticsearch-19.17.2
type: Opaque
data:
  elasticsearch-password: "QWRtaW5BZG1pbg=="
